### ISSUE TITLE
Have *nix iteration output show IP addr 

### ISSUE THREAD

**Issue by ericdorsey** [ericdorsey/HostMAC#5]
Windows screen output during iteration has format like:

```
192.168.1.3 HOSTNAME1 FF:AA:BB:CC:DD:0A
192.168.1.4 ANOTHERHOST BB:FF:AA:0F:DD:6A
```

Currently, *nix iteration shows:

```
16.9ms FOOHOST BB:AA:CC:DD:0A:6A
```

When running from *nix, screen feedback / iteration details to user should show IP address like when run from a Windows host (Including `ms` response as well is optional, but might be good to add this into the output for running from a Windows client, this would be a another issue though [ie, add `ms` response to output when running from Windows client]).

**Comment by bcambl** [comment]
Although adding a simple print statement to return the ip would fix this for *nix, perhaps there is a better solution.
- The function `getPing(ip)` should logically ONLY return the ping from an ip.
- Lines 126 & 145: `ping = getPing(ip)` do not appear to be used at all in the script.
- A print statement on line 71 prints the output of `getPing(ip)` and this seems to be where the script is returning the stdout IP when tested on windows (see lines 56-62)

I propose rewriting lines 56-62 to parse the Windows ping results with regex and send the ip to stdout elsewhere in the script  (`getOne` and `getAll`) since we already know the ip at that point.

I would be happy to update this PR if you provide some samples of successful and failed ping output via Windows.

**Comment by ericdorsey** [comment]
Absolutely want to look more into this! Let me check this out after work tonight and I'll have more of a response for you.

**Comment by ericdorsey** [comment]
Have a look at b56479813f0 and see if this it's basically what you had in mind?

I wrote this code initially a few years ago, then pushed it to GitHub later, and looking at getPing() it really wasn't doing anything for the results of the program... at all .. (hence your lines 126 & 145 comment). I standardized this to be the `ms` returned (for Win or *nix). Also, this.. 
- renames `getPing()` to more meaningful `getPing_msResponse()`
- replaces meaningless `subPing` variable name with `ping_msResponse` in `getPing_msResponse()`
- updated to use Regex, modeled after your *nix merges
- `getPing()` now has one job: returning `ms` time 
- standardized `getOne()` and `getAll()` to actually use returned `ms` in output, and..
- both Win and *nix now show the `ms` output when iterating through results

If we accept these changes:
- [x] we'd need a new header in `titleCheck()` (to accommodate `ms` response times) if the rest of this looks good
- [x] need to cleanup all my ugly debug comments 

Also, I think `getOne()` and `getAll()` can be streamlined into one function which takes an argument that determines if we're doing one thing, or the whole `1-254` range (opened #8 for this)

**Comment by bcambl** [comment]
Yup!
Test OK on Fedora with Python 2.7.8 and Windows 8 Python 2.7.9.
Cygwin on the other hand is a bit broken so maybe take that out of the README.md for now.

**Comment by ericdorsey** [comment]
Rad! Thanks for testing. I'll remove the Cygwin for now.

**Comment by ericdorsey** [comment]
Last commit 1d4cfb28cd covers the header and debug comment cleanup, too, from my comment above. 

I think this can be closed.

**Comment by ericdorsey** [comment]
Thank you for analysis / input / contributions!

Closing this one; re-open if you disagree.
